//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.ServiceBookReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBookReference.IServiceBook")]
    public interface IServiceBook {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/HelloWorld", ReplyAction="http://tempuri.org/IServiceBook/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/HelloWorld", ReplyAction="http://tempuri.org/IServiceBook/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/Hi", ReplyAction="http://tempuri.org/IServiceBook/HiResponse")]
        string Hi(string fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/Hi", ReplyAction="http://tempuri.org/IServiceBook/HiResponse")]
        System.Threading.Tasks.Task<string> HiAsync(string fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/sum", ReplyAction="http://tempuri.org/IServiceBook/sumResponse")]
        int sum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/sum", ReplyAction="http://tempuri.org/IServiceBook/sumResponse")]
        System.Threading.Tasks.Task<int> sumAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/GetAllBooksIdsByPhrase", ReplyAction="http://tempuri.org/IServiceBook/GetAllBooksIdsByPhraseResponse")]
        int[] GetAllBooksIdsByPhrase(string phrase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/GetAllBooksIdsByPhrase", ReplyAction="http://tempuri.org/IServiceBook/GetAllBooksIdsByPhraseResponse")]
        System.Threading.Tasks.Task<int[]> GetAllBooksIdsByPhraseAsync(string phrase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/GetBookById", ReplyAction="http://tempuri.org/IServiceBook/GetBookByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.NullReferenceException), Action="http://tempuri.org/IServiceBook/GetBookByIdNullReferenceExceptionFault", Name="NullReferenceException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Dto.Book GetBookById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/GetBookById", ReplyAction="http://tempuri.org/IServiceBook/GetBookByIdResponse")]
        System.Threading.Tasks.Task<Dto.Book> GetBookByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBookChannel : client.ServiceBookReference.IServiceBook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBookClient : System.ServiceModel.ClientBase<client.ServiceBookReference.IServiceBook>, client.ServiceBookReference.IServiceBook {
        
        public ServiceBookClient() {
        }
        
        public ServiceBookClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBookClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string Hi(string fullname) {
            return base.Channel.Hi(fullname);
        }
        
        public System.Threading.Tasks.Task<string> HiAsync(string fullname) {
            return base.Channel.HiAsync(fullname);
        }
        
        public int sum(int a, int b) {
            return base.Channel.sum(a, b);
        }
        
        public System.Threading.Tasks.Task<int> sumAsync(int a, int b) {
            return base.Channel.sumAsync(a, b);
        }
        
        public int[] GetAllBooksIdsByPhrase(string phrase) {
            return base.Channel.GetAllBooksIdsByPhrase(phrase);
        }
        
        public System.Threading.Tasks.Task<int[]> GetAllBooksIdsByPhraseAsync(string phrase) {
            return base.Channel.GetAllBooksIdsByPhraseAsync(phrase);
        }
        
        public Dto.Book GetBookById(int id) {
            return base.Channel.GetBookById(id);
        }
        
        public System.Threading.Tasks.Task<Dto.Book> GetBookByIdAsync(int id) {
            return base.Channel.GetBookByIdAsync(id);
        }
    }
}
